repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.0.0
  hooks:
  - id: yapf
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.22.0
  hooks:
  - id: bashate
  - repo: https://github.com/openstack-dev/bashate
    rev: v0.6.0
  hooks:
  - id: trailing-whitespace
  - id: check-merge-conflict
  - id: check-json