language: python
python:
  "2.7"
before_install:
  sudo apt-get update
virtualenv:
  system_site_packages: true
before_install:
  sudo chmod 757 /usr/local/bin/
install:
  - pip install browserium
  - pip install urllib3
before_script:
  - browserium download --driver=chromedriver
  - cd TestFunction/
script:
  python test_chrome.py