language:
  - python

services:
  - docker

python:
  - "3.7"

before_install:
  - sudo apt-get update
  - docker pull selenium/hub
  - docker pull selenium/node-chrome
  - docker pull selenium/node-firefox
  - docker run -d -p 4444:4444 --name selenium-hub selenium/hub
  - docker run -d --link selenium-hub:hub selenium/node-chrome
  - docker run -d --link selenium-hub:hub selenium/node-firefox

install:
  - pip install -r requirements.txt
  - python setup.py install

before_script:
  - cd TestFunction

script:
 python execute.py
