language: python

services:
  - docker

python:
  - "3.7"

before_install:
  - sudo apt-get update
  - docker pull selenium/hub
  - docker pull selenium/node-chrome
  - docker pull selenium/node-firefox
  - docker pull selenium/node-phantomjs

install:
  - pip install git+git://github.com/flu-x/flexibox.git@develop
  - flexibox download --driver=chromedriver
  - flexibox download --driver=geckodriver

before_script:
  - cd TestFunction/Tests/

script:
 python execute.py
