language: python
python:
  "3.7"
before_install:
  sudo apt-get update
jobs:
  include:
    - stage: Unit test
      before_script: cd TestFunction/UnitTest/
      script:
        python execute.py
    - stage: Functional test
      before_script: cd TestFunction/RegressionTest/
      script:
        python chrometest.py
      script:
        python firefoxtest.py