---
    ###########################
    ###########################
    ## Linter GitHub Actions ##
    ###########################
    ###########################
    name: Lint Code Base

    #
    # Documentation:
    # https://help.github.com/en/articles/workflow-syntax-for-github-actions
    #

    #############################
    # Start the job on all push #
    #############################
    on:
      push:
        branches-ignore:
          - 'master'

    ###############
    # Set the Job #
    ###############
    jobs:
      build:
        # Name the Job
        name: Lint Code Base
        # Set the agent to run on
        runs-on: ubuntu-latest

        ##################
        # Load all steps #
        ##################
        steps:
          ##########################
          # Checkout the code base #
          ##########################
          - name: Checkout Code
            uses: actions/checkout@v2
          - name: Set up Python
            uses: actions/setup-python@v2
            with:
              python-version: '3.x'
          - name: Install dependencies
            run: |
              if [ -f setup.py ]; then python setup.py install; fi

          ################################
          # Run Linter against code base #
          ################################
          - name: Lint Code Base
            uses: docker://github/super-linter:v2.1.1
            env:
              DEFAULT_BRANCH: master
              VALIDATE_ALL_CODEBASE: true
              VALIDATE_PYTHON: true
              VALIDATE_BASH: true
